version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: olist_postgres
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: olist_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - olist_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: olist_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - olist_network

networks:
  olist_network:

volumes:
  postgres_data: